apiVersion: v1
kind: ReplicationController
metadata:
  name: springboothc
spec:
  replicas: 2
  selector:
    name: springboothc
  template:
    metadata:
      name: springboothc
      labels:
        name: springboothc
    spec:
      containers:
      - name: springboothc
        image: deelthor/kube-springboot-hazelcast:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP