apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboothc
  name: springboothc
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    name: springboothc
  type: NodePort